spring:
  datasource:
    url: jdbc:h2:mem:cibseven-ex1;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

camunda:
  bpm:
    database:
      type: h2
