server:
  port: 8080

spring:
  config:
    import:
      - optional:classpath:cibseven-webclient.properties
  datasource:
    url: jdbc:postgresql://localhost:5432/cibseven-training
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

dev:
  bpm-crafters:
    process-api:
      worker:
        deployment:
          enabled: true
          bpmnResourcePattern: "classpath*:/**/*.bpmn"
          dmnResourcePattern: "classpath*:/**/*.dmn"
      adapter:
        cib-seven-embedded:
          enabled: true
          service-tasks:
            delivery-strategy: embedded_scheduled
            worker-id: worker
            schedule-delivery-fixed-rate-in-seconds: 5
          user-tasks:
            delivery-strategy: embedded_scheduled
            schedule-delivery-fixed-rate-in-seconds: 5

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: postgres
      schema-update: true

cibseven:
  webclient:
    services:
      basePath: services/v1
    # Engine rest
    engineRest:
      url: http://localhost:8080