package io.miragon.training.adapter.config;

import org.cibseven.rest.client.api.ProcessDefinitionApi;
import org.cibseven.rest.client.invoker.ApiClient;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.client.RestClient;

/**
 * Wires the two ways this service talks to the shared engine over {@code /engine-rest}:
 * <ul>
 *   <li>a plain {@link RestClient} for the multipart model deployment ({@code EngineDeploymentAdapter});</li>
 *   <li>the autogenerated typed {@link ProcessDefinitionApi} (from {@code cibseven-engine-client}) for
 *       driving the process ({@code RemoteWelcomeKitProcessAdapter}).</li>
 * </ul>
 * Both point at the same base URL the external-task client already uses.
 */
@Configuration
public class EngineClientConfig {

    @Bean
    public RestClient engineRestClient(@Value("${camunda.bpm.client.base-url}") String engineBaseUrl) {
        return RestClient.builder().baseUrl(engineBaseUrl).build();
    }

    @Bean
    public ApiClient cibsevenApiClient(@Value("${camunda.bpm.client.base-url}") String engineBaseUrl) {
        ApiClient apiClient = new ApiClient();
        apiClient.setBasePath(engineBaseUrl);
        return apiClient;
    }

    @Bean
    public ProcessDefinitionApi processDefinitionApi(ApiClient cibsevenApiClient) {
        return new ProcessDefinitionApi(cibsevenApiClient);
    }
}
