// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnFlow;
import io.miragon.bpmn.runtime.BpmnRelations;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.SignalName;
import java.lang.String;
import java.util.List;

public final class SendWelcomeKitProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("sendWelcomeKit");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  public static final class Elements {
    public static final ElementId END_EVENT_WELCOME_KIT_SHIPPED = new ElementId("endEvent_welcomeKitShipped");

    public static final ElementId SERVICE_TASK_SHIP_WELCOME_KIT = new ElementId("serviceTask_shipWelcomeKit");

    public static final ElementId START_EVENT_MEMBER_ACTIVATED = new ElementId("startEvent_memberActivated");
  }

  /**
   * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
   * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
   */
  public static final class ServiceTasks {
    public static final String SHIP_WELCOME_KIT = "shipWelcomeKit";
  }

  public static final class Signals {
    public static final SignalName SIGNAL_MEMBER_ACTIVATED = new SignalName("Signal_MemberActivated");
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  public static final class Flows {
    public static final BpmnFlow FLOW_TO_END = new BpmnFlow("Flow_toEnd", null, "serviceTask_shipWelcomeKit", "endEvent_welcomeKitShipped", null, false);

    public static final BpmnFlow FLOW_TO_SHIP_KIT = new BpmnFlow("Flow_toShipKit", null, "startEvent_memberActivated", "serviceTask_shipWelcomeKit", null, false);
  }

  /**
   * Per-element graph metadata (elementType / previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  public static final class Relations {
    public static final BpmnRelations END_EVENT_WELCOME_KIT_SHIPPED = new BpmnRelations("Welcome kit shipped", List.of("serviceTask_shipWelcomeKit"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations SERVICE_TASK_SHIP_WELCOME_KIT = new BpmnRelations("Ship welcome kit", List.of("startEvent_memberActivated"), List.of("endEvent_welcomeKitShipped"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations START_EVENT_MEMBER_ACTIVATED = new BpmnRelations("New member activated", List.of(), List.of("serviceTask_shipWelcomeKit"), null, null, List.of(), "SIGNAL_START_EVENT");
  }
}
