# Use this only in dev environments. It's not intended for production usage.
services:

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: cibseven-training
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    restart: always
