// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnFlow;
import io.miragon.bpmn.runtime.BpmnRelations;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.ProcessId;
import java.lang.String;
import java.util.List;

public final class EmployeeNotificationProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("employeeNotification");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  public static final class Elements {
    public static final ElementId END_EVENT_EMPLOYEES_NOTIFIED = new ElementId("endEvent_employeesNotified");

    public static final ElementId SERVICE_TASK_NOTIFY_EMPLOYEES = new ElementId("serviceTask_notifyEmployees");

    public static final ElementId START_EVENT_NEW_MEMBER = new ElementId("startEvent_newMember");
  }

  /**
   * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
   * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
   */
  public static final class ServiceTasks {
    public static final String NOTIFY_EMPLOYEES = "notifyEmployees";
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  public static final class Flows {
    public static final BpmnFlow FLOW_TO_END = new BpmnFlow("Flow_toEnd", null, "serviceTask_notifyEmployees", "endEvent_employeesNotified", null, false);

    public static final BpmnFlow FLOW_TO_NOTIFY = new BpmnFlow("Flow_toNotify", null, "startEvent_newMember", "serviceTask_notifyEmployees", null, false);
  }

  /**
   * Per-element graph metadata (previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  public static final class Relations {
    public static final BpmnRelations END_EVENT_EMPLOYEES_NOTIFIED = new BpmnRelations("Employees notified", List.of("serviceTask_notifyEmployees"), List.of(), null, null, List.of());

    public static final BpmnRelations SERVICE_TASK_NOTIFY_EMPLOYEES = new BpmnRelations("Notify employees", List.of("startEvent_newMember"), List.of("endEvent_employeesNotified"), null, null, List.of());

    public static final BpmnRelations START_EVENT_NEW_MEMBER = new BpmnRelations("New member joined", List.of(), List.of("serviceTask_notifyEmployees"), null, null, List.of());
  }
}
