server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cibseven-training?currentSchema=exercise5
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: exercise5

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: postgres
      schema-update: true

cibseven:
  webclient:
    services:
      basePath: services/v1
    engineRest:
      url: http://localhost:8086
